### ISSUE TITLE
Example description

### ISSUE THREAD

**Issue by Wuerike** [YangyangFu/docker_gym_pytorch_jmodelica#4]
Hey, great work you're doing here!

I'm doing my master thesis on RL applied on max power tracking on solar modules and the biggest problem so far it's being find some workable free enviroment to simulate models and control them with python RL Agent.

I've just found modelica, and I saw it has the models I need a that exists this possibilite to apply RL.

Could you add some readme to the example? 
I'd like to understand how to run it and what should I do to compile other modelica model to replace it.

**Comment by YangyangFu** [comment]
@Wuerike Yes I will add a cart pole example using DRL for tutorial soon. 

This will be in `issue4_addRLExamples`.

**Comment by YangyangFu** [comment]
resolved.
